/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorkspaceIdRouteRouteImport } from './routes/app/$workspaceId/route'
import { Route as AppWorkspaceIdWriteRouteImport } from './routes/app/$workspaceId/write'
import { Route as AppWorkspaceIdSettingsRouteImport } from './routes/app/$workspaceId/settings'
import { Route as AppWorkspaceIdDocumentsRouteImport } from './routes/app/$workspaceId/documents'
import { Route as AppWorkspaceIdChatRouteImport } from './routes/app/$workspaceId/chat'
import { Route as AppWorkspaceIdAuditRouteImport } from './routes/app/$workspaceId/audit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdRouteRoute = AppWorkspaceIdRouteRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdWriteRoute = AppWorkspaceIdWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdSettingsRoute = AppWorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdDocumentsRoute = AppWorkspaceIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdChatRoute = AppWorkspaceIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdAuditRoute = AppWorkspaceIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$workspaceId/audit': typeof AppWorkspaceIdAuditRoute
  '/app/$workspaceId/chat': typeof AppWorkspaceIdChatRoute
  '/app/$workspaceId/documents': typeof AppWorkspaceIdDocumentsRoute
  '/app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRoute
  '/app/$workspaceId/write': typeof AppWorkspaceIdWriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/$workspaceId/audit': typeof AppWorkspaceIdAuditRoute
  '/app/$workspaceId/chat': typeof AppWorkspaceIdChatRoute
  '/app/$workspaceId/documents': typeof AppWorkspaceIdDocumentsRoute
  '/app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRoute
  '/app/$workspaceId/write': typeof AppWorkspaceIdWriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$workspaceId/audit': typeof AppWorkspaceIdAuditRoute
  '/app/$workspaceId/chat': typeof AppWorkspaceIdChatRoute
  '/app/$workspaceId/documents': typeof AppWorkspaceIdDocumentsRoute
  '/app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRoute
  '/app/$workspaceId/write': typeof AppWorkspaceIdWriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/$workspaceId'
    | '/app/'
    | '/app/$workspaceId/audit'
    | '/app/$workspaceId/chat'
    | '/app/$workspaceId/documents'
    | '/app/$workspaceId/settings'
    | '/app/$workspaceId/write'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/$workspaceId'
    | '/app'
    | '/app/$workspaceId/audit'
    | '/app/$workspaceId/chat'
    | '/app/$workspaceId/documents'
    | '/app/$workspaceId/settings'
    | '/app/$workspaceId/write'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/$workspaceId'
    | '/app/'
    | '/app/$workspaceId/audit'
    | '/app/$workspaceId/chat'
    | '/app/$workspaceId/documents'
    | '/app/$workspaceId/settings'
    | '/app/$workspaceId/write'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId': {
      id: '/app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/app/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId/write': {
      id: '/app/$workspaceId/write'
      path: '/write'
      fullPath: '/app/$workspaceId/write'
      preLoaderRoute: typeof AppWorkspaceIdWriteRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/app/$workspaceId/settings': {
      id: '/app/$workspaceId/settings'
      path: '/settings'
      fullPath: '/app/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/app/$workspaceId/documents': {
      id: '/app/$workspaceId/documents'
      path: '/documents'
      fullPath: '/app/$workspaceId/documents'
      preLoaderRoute: typeof AppWorkspaceIdDocumentsRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/app/$workspaceId/chat': {
      id: '/app/$workspaceId/chat'
      path: '/chat'
      fullPath: '/app/$workspaceId/chat'
      preLoaderRoute: typeof AppWorkspaceIdChatRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/app/$workspaceId/audit': {
      id: '/app/$workspaceId/audit'
      path: '/audit'
      fullPath: '/app/$workspaceId/audit'
      preLoaderRoute: typeof AppWorkspaceIdAuditRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
  }
}

interface AppWorkspaceIdRouteRouteChildren {
  AppWorkspaceIdAuditRoute: typeof AppWorkspaceIdAuditRoute
  AppWorkspaceIdChatRoute: typeof AppWorkspaceIdChatRoute
  AppWorkspaceIdDocumentsRoute: typeof AppWorkspaceIdDocumentsRoute
  AppWorkspaceIdSettingsRoute: typeof AppWorkspaceIdSettingsRoute
  AppWorkspaceIdWriteRoute: typeof AppWorkspaceIdWriteRoute
}

const AppWorkspaceIdRouteRouteChildren: AppWorkspaceIdRouteRouteChildren = {
  AppWorkspaceIdAuditRoute: AppWorkspaceIdAuditRoute,
  AppWorkspaceIdChatRoute: AppWorkspaceIdChatRoute,
  AppWorkspaceIdDocumentsRoute: AppWorkspaceIdDocumentsRoute,
  AppWorkspaceIdSettingsRoute: AppWorkspaceIdSettingsRoute,
  AppWorkspaceIdWriteRoute: AppWorkspaceIdWriteRoute,
}

const AppWorkspaceIdRouteRouteWithChildren =
  AppWorkspaceIdRouteRoute._addFileChildren(AppWorkspaceIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceIdRouteRoute: typeof AppWorkspaceIdRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceIdRouteRoute: AppWorkspaceIdRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
